---
- name: Copy .bash_aliases into position
  template:
    src: "home/bash_aliases.j2"
    dest: "{{item}}"
  with_items:
    - "/home/{{defaultuser.name}}/.bash_aliases"
  when: bash_aliases is defined
  tags:
    - bash_aliases