---
# tasks file for docker-configure

- name: Configure base-os
  include: base-os.yml
  tags: baseos

- name: Install docker compose on arm64
  include: docker-compose.yml
  tags: dockercompose
  when: ansible_architecture != "x86_64"

- name: Configure users
  include: users.yml
  tags: users

- name: Configure aliases
  include: aliases.yml
  tags: aliases

- name: Configure docker apps
  include: docker-apps.yml
  tags: dockerapps
