---
# tasks file for docker-configure

- name: Configure base-os
  include_tasks: base-os.yml
  tags: baseos

- name: Configure users
  include_tasks: users.yml
  tags: users

- name: Configure aliases
  include_tasks: aliases.yml
  tags: aliases

- name: Configure docker apps
  include_tasks: docker-apps.yml
  tags: dockerapps
